### ISSUE TITLE
_RSAobj object has no 'export_key' attribute

### ISSUE THREAD

**Issue by bshensky** [evan-goode/duolibre#2]
Soooo close!  I've got py3 and all the pip3'd dependencies installed.  
Then I run to the Duo device registration and get the URL:
https://m-d9c5afcf.duosecurity.com/android/2xVRQjwT0kszoz******
Then I post the command to my Ubuntu 20.04 LTS box at Azure:
bshensky@myserver:~/duolibre/duolibre$ ./duolibre.py  https://m-d9c5afcf.duosecurity.com/android/2xVRQjwT0kszoz******
Result:
Traceback (most recent call last):
  File "./duolibre.py", line 78, in <module>
    duolibre()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./duolibre.py", line 59, in duolibre
    secret = get_secret(activation_uri)
  File "./duolibre.py", line 37, in get_secret
    "pubkey": RSA.generate(2048).publickey().export_key().decode(),
  File "/usr/lib/python3/dist-packages/Crypto/PublicKey/RSA.py", line 126, in __getattr__
    raise AttributeError("%s object has no %r attribute" % (self.__class__.__name__, attrname,))
AttributeError: _RSAobj object has no 'export_key' attribute

Any ideas?

**Comment by evan-goode** [comment]
Closing this cause it's old, sorry I didn't see it. You may have installed pycryptodome instead of pycrypto?

For future users, the `python3 -m pip install --user duolibre` is the recommended installation method.
